# -*- coding: utf-8 -*-
"""resume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-O8VppHHCkm0p7mnj47yIgsHQutigl87
"""

!pip install scikit-learn pandas joblib numpy
!pip install transformers datasets evaluate accelerate sentencepiece  # required dependencies are installed
!pip install torch

import random
import os
from typing import List

import pandas as pd
import numpy as np
import joblib
import os
os.environ["WANDB_DISABLED"] = "true"

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix

def make_synthetic_resume_dataset(n_samples=1000, pos_ratio=0.5, random_state=42):
    random.seed(random_state)
    np.random.seed(random_state)

    ds_phrases = [
        "machine learning", "deep learning", "data science", "data analysis",
        "python", "pandas", "numpy", "scikit-learn", "tensorflow", "pytorch",
        "modeling", "feature engineering", "statistical analysis", "natural language processing",
        "classification", "regression", "clustering", "SQL", "big data", "spark"
    ]

    non_ds_phrases = [
        "accounting", "sales", "marketing", "customer service", "biology", "chemistry",
        "product management", "graphic design", "illustrator", "photoshop", "content writing",
        "teaching", "cashier", "retail", "hospitality"
    ]

    texts, labels = [], []
    for i in range(n_samples):
        if random.random() < pos_ratio:
            words = random.choices(ds_phrases + non_ds_phrases, weights=[3]*len(ds_phrases) + [1]*len(non_ds_phrases), k=random.randint(20, 60))
            labels.append(1)
        else:
            words = random.choices(non_ds_phrases + ds_phrases, weights=[3]*len(non_ds_phrases) + [0.5]*len(ds_phrases), k=random.randint(20, 60))
            labels.append(0)
        texts.append(" ".join(words))

    return pd.DataFrame({"text": texts, "label": labels})

def train_level1(df: pd.DataFrame, model_type="logreg"):
    X = df['text'].values
    y = df['label'].values
    X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

    if model_type == 'logreg':
        clf = LogisticRegression(max_iter=1000)
    else:
        clf = MultinomialNB()

    pipe = Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1,2), min_df=2)),
        ('clf', clf)
    ])

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    print("Classification report:")
    print(classification_report(y_test, y_pred))
    print("Confusion matrix:")
    print(confusion_matrix(y_test, y_pred))

    return pipe

df = make_synthetic_resume_dataset(n_samples=1200)
pipe = train_level1(df)

example_resume = "Experienced in machine learning, Python, pandas, statistical analysis and model deployment" # testing an example resume line
prediction = pipe.predict([example_resume])[0]
print("\nExample resume prediction (1=DS, 0=non-DS):", prediction)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
test_df = pd.read_csv("resume.csv")
y_true = test_df['label'].values
y_pred = pipe.predict(test_df['text'].values)

cm = confusion_matrix(y_true, y_pred, labels=[1,0])
disp = ConfusionMatrixDisplay(cm, display_labels=["DS", "Non-DS"])
disp.plot(cmap="Blues")

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred, target_names=["Non-DS","DS"]))

texts = df['text'].values
y_true = df['label'].values
y_probs = pipe.predict_proba(texts)[:,1]

fpr, tpr, thresholds = roc_curve(y_true, y_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, color='blue', label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1],[0,1], color='red', linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, DataCollatorWithPadding
import evaluate
import numpy as np

def level2_train_script(train_texts, train_labels, val_texts, val_labels,
                        model_name='distilbert-base-uncased', output_dir='./hf_model',
                        num_train_epochs=1, per_device_batch_size=8):

    train_ds = Dataset.from_dict({"text": train_texts, "label": train_labels})
    val_ds = Dataset.from_dict({"text": val_texts, "label": val_labels})
    ds = DatasetDict({"train": train_ds, "validation": val_ds})


    tokenizer = AutoTokenizer.from_pretrained(model_name)
    def tokenize_fn(batch):
        return tokenizer(batch['text'], truncation=True, padding='max_length', max_length=128)
    tokenized = ds.map(tokenize_fn, batched=True)


    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
    metric = evaluate.load('accuracy')

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        return {"accuracy": metric.compute(predictions=preds, references=labels)['accuracy']}


    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=per_device_batch_size,
        per_device_eval_batch_size=per_device_batch_size,
        logging_steps=50,
        do_train=True,
        do_eval=True,
        load_best_model_at_end=False
    )


    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized['train'],
        eval_dataset=tokenized['validation'],
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )


    trainer.train()
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)
    return output_dir

!pip install --upgrade transformers datasets evaluate accelerate
!pip install --upgrade torch

df2 = make_synthetic_resume_dataset(n_samples=400)
X = df2['text'].tolist()
y = df2['label'].tolist()
X_train, X_val, y_train, y_val = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

print("Training DistilBERT (quick demo, 1 epoch)...")
model_dir = level2_train_script(X_train, y_train, X_val, y_val, num_train_epochs=1)
print("Model saved at:", model_dir)

import pandas as pd
df_real = pd.read_csv("resume.csv").dropna(subset=["text","label"])

# Save TF-IDF model
joblib.dump(pipe, "level1_pipe.joblib")

# Fine-tuned DistilBERT  saved as ./hf_model

!pip install -q ctransformers

from ctransformers import AutoModelForCausalLM

# Load the LLaMA 2 7B model
model = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-7b-Chat-GGML")

from ctransformers import AutoModelForCausalLM

# Load the model (7B Chat model)
model = AutoModelForCausalLM.from_pretrained("TheBloke/Llama-2-7b-Chat-GGML")

# Function to generate interview questions prompt
def generate_interview_questions(resume_text: str, job_title: str):
    return f"""
Generate a set of 5 interview questions for a {job_title} role based on the following resume:

{resume_text}
"""

# Function to get model response
def get_interview_questions(prompt: str):
    # Use .generate with default arguments
    response = model.generate(prompt)
    return response

resume_text = "Python developer with experience in data cleaning, wrangling, and analysis"
job_title = "Data Analyst"

prompt = generate_interview_questions(resume_text, job_title)
interview_questions = get_interview_questions(prompt)

print("Generated Interview Questions:\n")
print(interview_questions)

def generate_interview_questions_prompt(resume_text: str, role: str = "Data Scientist") -> str:
    return f"""
You are an experienced interviewer for {role} positions. Given the following resume, create:
1) 8 targeted technical questions (easy/medium/hard).
2) 4 behavioral questions.
3) For the top 3 technical questions, give a short rubric.

Resume:
{resume_text}
"""

# Example
sample_resume = X_val[0]
print(generate_interview_questions_prompt(sample_resume))

!pip install fpdf

from fpdf import FPDF

user_resume = input("Paste your resume text here:\n")
user_job_title = input("Specify the job title you're targeting:\n")

prediction = pipe.predict([user_resume])[0]
label = "Data Scientist" if prediction == 1 else "Non-DS"
print(f"\nDS / Non-DS Prediction: {label}")

short_resume = user_resume[:200]  # first 200 characters
prompt = f"Generate 5 interview questions for a {user_job_title} role based on this resume: {short_resume}"

try:
    questions_text = model(prompt)
except TypeError:
    questions_text = model.generate(prompt)

pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 8, f"DS / Non-DS Prediction: {label}\n\n")
pdf.multi_cell(0, 8, "Generated Interview Questions:\n\n" + questions_text)
pdf_file = "Interview_Questions.pdf"
pdf.output(pdf_file)

print(f"\n✅ Interview questions saved as PDF: {pdf_file}")